name: "Test"

on:
  push:
    #branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    #branches: [ master ]

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        os-version: [ ubuntu-24.04, ubuntu-22.04 ]
        compiler: [ latest, gcc-latest, gcc-15, g++-12, clang, clang-20, clang++-19, clang-16, clang++-15 ]
        exclude:
         - os-version: ubuntu-24.04
           compiler: gcc-15
         - os-version: ubuntu-22.04
           compiler: gcc-15
         - os-version: ubuntu-22.04
           compiler: clang-20
         - os-version: ubuntu-22.04
           compiler: clang++-19
         - os-version: ubuntu-22.04
           compiler: clang-16

    runs-on: ${{ matrix.os-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.compiler }}

      - name: Check compiler
        shell: bash
        env:
            CC: ${{ steps.install_cc.outputs.cc }}
            CXX: ${{ steps.install_cc.outputs.cxx }}
        run: |
          $CC --version
          $CXX --version

  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os-version: [ macos-26, macos-15, macos-14 ]
        compiler: [ gcc, gcc-14, g++-11, clang, clang-21, clang++-14 ]

    runs-on: ${{ matrix.os-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.compiler }}

      - name: Check compiler
        shell: bash
        env:
            CC: ${{ steps.install_cc.outputs.cc }}
            CXX: ${{ steps.install_cc.outputs.cxx }}
        run: |
          $CC --version
          $CXX --version

  test-win:
    strategy:
      fail-fast: false
      matrix:
        os-version: [ windows-2025m windows-2022 ]
        compiler: [ latest, gcc-latest, gcc-6.4.0, gcc-10.2.0, g++-11.2.0, clang, clang-8.0.0, clang-11.1.0, clang++-12.0.1 ]

    runs-on: ${{ matrix.os-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.compiler }}

      - name: Check compiler
        shell: bash
        env:
            CC: ${{ steps.install_cc.outputs.cc }}
            CXX: ${{ steps.install_cc.outputs.cxx }}
        run: |
          $CC --version
          $CXX --version
